# Generated by Django 4.2.11 on 2024-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='paragraph',
            field=models.CharField(default=-2024, max_length=250),
            preserve_default=False,
        ),
    ]
